"""The generated index: a pure function of the entry files, and the refusal that keeps
regenerating it from destroying what only it holds.
"""

from __future__ import annotations

import posixpath
import re
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING

from keelline.config.paths import contained
from keelline.errors import Refusal
from keelline.identifiers import identifiers
from keelline.ledger.entries import Entry, bugs_dir

if TYPE_CHECKING:
    from keelline.config.schema import Config

GENERATED_BY = "_Generated by `keelline bugs index`"
# Structural recognition: the first paragraph opens with the marker's fixed prefix and names
# `index` inside the backticks. This also recognises the generator this one replaced, whose
# sentence differed only in the invocation (Premise 4).
_GENERATED = re.compile(r"\A_Generated by `[^`\n]*\bindex\b[^`\n]*` from ")
_LIVE_COLUMNS = "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
_FIXED_COLUMNS = "| ID | Title | Fixed in |\n|---|---|---|\n"
SECTIONS = (
    ("open", "Open"),
    ("partial", "Partially fixed"),
    ("rejected", "Rejected"),
    ("fixed", "Fixed"),
    ("void", "Void identifiers"),
)
# `SECTIONS` and `STATUSES` are pinned equal as sets by
# `test_every_status_has_a_section_to_be_rendered_into`, which pins this reading order
# separately as a literal; no module-level `assert`, which `python -O` would drop.
_SECTION_COUNT = re.compile(r"\A## (.+) \(\d+\)\Z")
# The two refusals, as format strings: `refuse_index_overwrite` raises them and `check.problems`
# reports them, and both must describe the same file the same way (`bugs`, `index`, `count`,
# `first` are the fields).
ENTRIES_MISSING = (
    "{bugs}/ does not exist, but {index} is this tool's generated index; the entry files are "
    "the ledger and the index carries nothing of its own, so restore them rather than "
    "regenerating over it"
)
# `{first!r}` is repository-authored text inside a `Refusal` message, and deliberately so: this
# message reaches the terminal of the person who ran the command against their own repository,
# which is the one reader the rule permits, and quoting the line is what makes the refusal
# actionable — without it the operator is told a line exists but not which.
FOREIGN_CONTENT = (
    "{index} carries {count} line(s) this tool did not generate, the first being {first!r}; "
    "the index is rendered from the entry files alone, so that content exists nowhere else — "
    "recover it before regenerating"
)


def _relative(config: Config, target: str) -> str:
    """`target` (a root-relative config path) as a link from the index's own directory."""
    index_dir = str(PurePosixPath(config.paths.bug_index).parent)
    return posixpath.relpath(target, index_dir)


def header(config: Config) -> str:
    bugs = _relative(config, config.paths.bugs)
    runbook = _relative(config, f"{config.paths.runbooks}/bug-reports.md")
    prefix = identifiers(config).prefix
    return (
        "# Bug reports\n\n"
        f"{GENERATED_BY} from `{bugs}/{prefix}-*.md`; edit the entry\n"
        "files, not this one. How to file, close, reference, and merge:\n"
        f"[runbook]({runbook}). Audit provenance: "
        f"[{config.paths.bugs}/audits/]({bugs}/audits/)._\n"
    )


def index_path(root: Path, config: Config) -> Path:
    return contained(root, config.paths.bug_index)


def index_text(root: Path, config: Config) -> str:
    """The committed index's text, or `""` where there is no index yet."""
    path = index_path(root, config)
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def _cell(text: str) -> str:
    """Keep a value inside its table cell: `|` would end the column, a newline the row.

    The backslash is escaped first, and it has to be: escaping only the pipe renders a title
    containing `\\|` as an escaped backslash followed by a live separator, which gives that row
    one column more than its header and slides the Found date under the wrong heading. Both
    readers of the index share this escaper, so the staleness check sees nothing wrong with it.
    """
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _link(entry: Entry, config: Config) -> str:
    return f"[{entry.id}]({_relative(config, config.paths.bugs)}/{entry.id}.md)"


def render_index(entries: list[Entry], config: Config) -> str:
    """The whole of the index file, from the entry files alone.

    Rows appear in the order `entries` arrives in, grouped into `SECTIONS` by status — the
    numeric ordering is `load_entries`' guarantee, not this function's, and every caller here
    goes through it. Nothing about the index is stored: it is a pure function of the entry
    files, which is what lets the staleness check decide by rendering and comparing.
    """
    parts = [header(config)]
    by_status = {status: [e for e in entries if e.status == status] for status, _ in SECTIONS}
    for status, heading in SECTIONS:
        selected = by_status[status]
        parts.append(f"\n## {heading} ({len(selected)})\n\n")
        if status == "fixed":
            parts.append(_FIXED_COLUMNS)
            parts.extend(
                f"| {_link(e, config)} | {_cell(e.title)} | {_cell(e.fixed_in)} |\n"
                for e in selected
            )
        elif status == "void":
            parts.append("| ID | Why |\n|---|---|\n")
            parts.extend(f"| {_link(e, config)} | {_cell(e.title)} |\n" for e in selected)
        else:
            parts.append(_LIVE_COLUMNS)
            parts.extend(
                f"| {_link(e, config)} | {e.severity} | {_cell(e.area)} | "
                f"{_cell(e.title)} | {e.found} |\n"
                for e in selected
            )
    return "".join(parts)


def is_generated_index(text: str) -> bool:
    """Whether this index is one this tool wrote, rather than a hand-written ledger."""
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        return False
    start = 1
    while start < len(lines) and not lines[start].strip():
        start += 1
    end = start
    while end < len(lines) and lines[end].strip():
        end += 1
    return _GENERATED.match("\n".join(lines[start:end])) is not None


def _generated_header_lines(text: str) -> list[str]:
    """The title and the first paragraph, when that paragraph is this tool's marker; else [].

    Recognised by structure rather than by matching `header()` literally: the `# ` title line
    and the first paragraph under it, which has to carry the generator marker. Both are
    rewritten by every regeneration, so a difference there loses nothing that is not also in
    this module — while reading them literally made any future edit to the header's prose turn
    every committed index into content "this tool did not generate", refusing the regeneration
    with `recover it before regenerating` about the one text in that file whose home is
    `header()` above, and pointing away from the fix. A reworded header is now what it is: a
    stale index, whose remedy is the regeneration.

    Deliberately just those: the title and that one paragraph. A line an operator added below
    them is separated by the blank line that ends the paragraph, so it stays foreign — which is
    the content the guard exists for, and the property this must not trade away.
    """
    if not is_generated_index(text):
        return []
    lines = text.splitlines()
    start = 1
    while not lines[start].strip():
        start += 1
    end = start
    while end < len(lines) and lines[end].strip():
        end += 1
    return [lines[0], *lines[start:end]]


def foreign_index_lines(text: str, config: Config) -> list[str]:
    """Every line of the committed index outside the grammar `render_index` writes.

    That grammar is the whole of what an index may hold: the header, one `## <Heading> (N)` per
    section, table headers and `| … |` rows, and blank lines. The regeneration renders the file
    from the entry files alone, so anything else in it lives only there and that write deletes
    it — with no diff, no prompt, and exit 0.

    Asked as line shapes rather than as a re-render, because "does regenerating destroy
    something" is a different question from "is this index current". A stale generated index
    destroys nothing and its remedy is to regenerate; a heading with two spaces after its
    `##`, a `###` one, and a prose section with no identifier at all survive nowhere else.
    Those shapes are spelled out in this guard's own tests, not here: writing one down in a
    scanned root would make this comment the dangling reference the scan exists to catch.
    """
    allowed = set(header(config).splitlines()) | set(_generated_header_lines(text))
    headings = {heading for _, heading in SECTIONS}
    foreign: list[str] = []
    for line in text.splitlines():
        if not line.strip() or line in allowed or line.startswith("|"):
            continue
        counted = _SECTION_COUNT.match(line)
        if counted is not None and counted.group(1) in headings:
            continue
        foreign.append(line)
    return foreign


def refuse_index_overwrite(root: Path, config: Config, current: str) -> None:
    """Refuse to regenerate while that write would destroy something (Premise 2 and 4).

    The regeneration renders the index from the entry files alone, so anything the committed
    file holds of its own is deleted by that write — with no diff to review, no prompt, and
    exit 0. In a merge whose operator resolved the index to the wrong side it is whichever
    sections only that side carried; it is unrecoverable once the merge is committed, and
    filing a bug reaches the same write, so `bugs new` must not be what destroys the ledger
    either.

    Two refusals: entry files that have vanished from under a generated index name their own
    restoration, and anything else outside the generated grammar can only be recovered by
    hand. Neither names a command, because the regeneration is the destruction rather than
    the repair.
    """
    index = config.paths.bug_index
    if not bugs_dir(root, config).is_dir() and is_generated_index(current):
        raise Refusal(ENTRIES_MISSING.format(bugs=config.paths.bugs, index=index))
    foreign = foreign_index_lines(current, config)
    if foreign:
        raise Refusal(FOREIGN_CONTENT.format(index=index, count=len(foreign), first=foreign[0]))
