"""The machine ledger every scaffolded artifact is recorded in (§7.1).

The manifest is committed, so `upgrade` and `uninstall` work for a collaborator who never ran
`init`. It is also the only reason `skip_modified` can exist: without a recorded hash there is
no way to tell a file the tool wrote from a file a person wrote, and every refresh would be
either a clobber or a no-op. It carries a `format` so a later migration can key on it (§7.3),
and it is written atomically, because it is the one file whose corruption bricks both
`upgrade` and `uninstall`.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from enum import StrEnum
from pathlib import Path

from keelline.errors import Refusal
from keelline.fsops import write_atomically

MANIFEST_PATH = Path(".keelline") / "manifest.json"
FORMAT = 1

GENERATED = (
    "Generated by keelline; do not hand-edit. Removing a record makes `upgrade` treat the "
    "file as foreign and `uninstall` leave it behind."
)


class ManifestError(Refusal):
    """A manifest that cannot be trusted: unreadable, malformed, or carrying unknown values."""


class Kind(StrEnum):
    TEMPLATE = "template"
    MANAGED_REGION = "managed-region"
    KEYED_ENTRIES = "keyed-entries"
    ONCE = "once"


class Location(StrEnum):
    REPO = "repo"
    LOCAL = "local"


@dataclass(frozen=True)
class Record:
    id: str
    kind: Kind
    location: Location
    target: str
    template: str
    version: str
    sha256: str


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _record_from(raw: object, key: str) -> Record:
    if not isinstance(raw, dict):
        raise ManifestError(f"artifact {key!r} is not a table")
    try:
        kind = Kind(raw["kind"])
        location = Location(raw["location"])
        return Record(
            id=str(raw["id"]),
            kind=kind,
            location=location,
            target=str(raw["target"]),
            template=str(raw["template"]),
            version=str(raw["version"]),
            sha256=str(raw["sha256"]),
        )
    except ValueError as exc:
        raise ManifestError(f"artifact {key!r}: {exc}") from exc
    except KeyError as exc:
        raise ManifestError(f"artifact {key!r} is missing {exc.args[0]!r}") from exc


@dataclass(frozen=True)
class Manifest:
    records: dict[str, Record]
    format: int = FORMAT

    @classmethod
    def read(cls, root: Path) -> Manifest:
        path = root / MANIFEST_PATH
        if not path.is_file():
            return cls({})
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ManifestError(f"{MANIFEST_PATH} is unreadable: {exc}") from exc
        if not isinstance(raw, dict):
            raise ManifestError(f"{MANIFEST_PATH} is not a JSON object")
        version = raw.get("format", FORMAT)
        if not isinstance(version, int) or version > FORMAT:
            raise ManifestError(
                f"{MANIFEST_PATH} was written by a newer Keelline (format {version!r}); "
                "upgrade the plugin rather than editing it"
            )
        artifacts = raw.get("artifacts", {})
        if not isinstance(artifacts, dict):
            raise ManifestError(f"{MANIFEST_PATH}: 'artifacts' is not an object")
        return cls({key: _record_from(value, key) for key, value in artifacts.items()}, version)

    def write(self, root: Path) -> Path:
        path = root / MANIFEST_PATH
        body = {
            "_generated": GENERATED,
            "format": FORMAT,
            "artifacts": {key: asdict(self.records[key]) for key in sorted(self.records)},
        }
        write_atomically(path, json.dumps(body, indent=2) + "\n")
        return path

    def get(self, artifact_id: str) -> Record | None:
        return self.records.get(artifact_id)

    def with_record(self, record: Record) -> Manifest:
        return Manifest({**self.records, record.id: record}, self.format)

    def without(self, ids: frozenset[str]) -> Manifest:
        return Manifest({k: v for k, v in self.records.items() if k not in ids}, self.format)
