"""A write or removal git would never show is refused, before anything is written, by all three
footprint commands; a tracked file, Keelline's own out-of-git directory, and a tree that is not a
repository are not."""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import pytest

import keelline
from keelline.config.loader import CONFIG_FILE
from keelline.errors import Refusal
from keelline.gitenv import git_run
from keelline.project import ignored as module
from keelline.project.ignored import IGNORED, UNANSWERED
from keelline.project.init import init
from keelline.project.uninstall import uninstall
from keelline.project.upgrade import upgrade
from keelline.scaffold import Manifest, digest
from tests.gitfixture import LsRemote, git, needs_git, run_git
from tests.project.repos import initialised
from tests.snapshot import assert_snapshot_unchanged, snapshot

ENV_TEXT = "ENV_TEXT=1\n"
MARKER = "generated by a tool\n"


def _upgrade(root: Path, tmp_path: Path, *, dry_run: bool = False) -> None:
    upgrade(root, machine=tmp_path / "absent.toml", runner=LsRemote(), dry_run=dry_run, force=())


def _uninstall(root: Path, tmp_path: Path, *, dry_run: bool = False) -> None:
    uninstall(root, machine=tmp_path / "absent.toml", dry_run=dry_run, force=())


def _append(path: Path, text: str) -> None:
    path.write_text(path.read_text(encoding="utf-8") + text, encoding="utf-8")


def _ignoring(root: Path, pattern: str) -> None:
    # A line of the project's own, outside Keelline's region.
    _append(root / ".gitignore", f"{pattern}\n")


@needs_git
@pytest.mark.parametrize("dry_run", [False, True], ids=["real", "dry-run"])
def test_a_committed_path_naming_an_ignored_env_file_is_refused_before_upgrade_writes(
    tmp_path: Path, dry_run: bool
) -> None:
    """The review's reproduction, end to end. `agents_md = ".env"` with `.env` git-ignored had
    `upgrade` report `region_update .env (refreshed)` and append Keelline's region to `.env`,
    while `git status` showed only the manifest. It is refused now, dry run included, naming a
    count and never the path, and nothing is written anywhere.

    Mutation (oracle): "a write git ignores goes ahead" -> the region lands in `.env` and the
    refusal is never raised.
    """
    root = initialised(tmp_path)
    _ignoring(root, ".env")
    (root / ".env").write_text(ENV_TEXT, encoding="utf-8")
    _append(root / CONFIG_FILE, '\n[paths]\nagents_md = ".env"\n')
    before = snapshot(root)
    with pytest.raises(Refusal) as refused:
        _upgrade(root, tmp_path, dry_run=dry_run)
    assert str(refused.value) == IGNORED.format(count=1)
    assert ".env" not in str(refused.value)
    assert (root / ".env").read_text(encoding="utf-8") == ENV_TEXT
    assert_snapshot_unchanged(root, before)


@needs_git
def test_init_refuses_a_path_git_ignores_and_writes_nothing(tmp_path: Path) -> None:
    root = tmp_path / "widget"
    root.mkdir()
    git(root, "init", "-q", "-b", "main")
    (root / ".gitignore").write_text(".env\n", encoding="utf-8")
    (root / ".env").write_text(ENV_TEXT, encoding="utf-8")
    (root / CONFIG_FILE).write_text(
        f'[keelline]\nversion = "{keelline.__version__}"\n\n[project]\nname = "widget"\n\n'
        '[paths]\nagents_md = ".env"\n\n[ci]\nmode = "none"\n',
        encoding="utf-8",
    )
    before = snapshot(root)
    with pytest.raises(Refusal) as refused:
        init(
            root,
            machine=tmp_path / "absent.toml",
            runner=LsRemote(),
            yes=True,
            dry_run=False,
            ci=False,
        )
    # One file, though the skeleton and the region both target it: a count of files, not of
    # actions.
    assert str(refused.value) == IGNORED.format(count=1)
    assert_snapshot_unchanged(root, before)


def _forge_roadmap(root: Path, target: str, text: str) -> None:
    """A commit pointing `roadmap` at `target` and recording `text`'s digest there."""
    _append(root / CONFIG_FILE, f'\n[paths]\nroadmap = "{target}"\n')
    manifest = Manifest.read(root)
    record = manifest.get("roadmap")
    assert record is not None
    manifest.with_record(replace(record, target=target, sha256=digest(text))).write(root)


@needs_git
@pytest.mark.parametrize(("command", "count"), [("upgrade", 2), ("uninstall", 1)])
def test_a_record_stating_a_predictable_ignored_file_reaches_it_for_neither_command(
    tmp_path: Path, command: str, count: int
) -> None:
    # A committed `[paths]` value and a record carrying the digest of a tool-generated file under
    # an ignored directory had `uninstall` delete it and `upgrade` overwrite it with the roadmap:
    # the record's digest matched, and git showed nothing. Mutation (oracle): "a write git
    # ignores goes ahead" -> the marker is removed or rewritten. `upgrade` also counts the
    # trail it would create beside the moved roadmap, under the same ignored directory.
    root = initialised(tmp_path)
    _ignoring(root, "build/")
    marker = root / "build" / "marker.txt"
    marker.parent.mkdir()
    marker.write_text(MARKER, encoding="utf-8")
    _forge_roadmap(root, "build/marker.txt", MARKER)
    before = snapshot(root)
    with pytest.raises(Refusal) as refused:
        (_upgrade if command == "upgrade" else _uninstall)(root, tmp_path)
    assert str(refused.value) == IGNORED.format(count=count)
    assert marker.read_text(encoding="utf-8") == MARKER
    assert_snapshot_unchanged(root, before)


@needs_git
def test_a_tracked_file_matching_an_ignore_pattern_is_not_ignored(tmp_path: Path) -> None:
    # `check-ignore` without `--no-index`: git shows every change to a tracked file, whatever
    # pattern it matches, so the region may go into one. Mutation (advisory): add `--no-index`
    # -> the tracked file reads as ignored and this run refuses.
    root = initialised(tmp_path)
    _ignoring(root, "notes/")
    host = root / "notes" / "AGENTS.md"
    host.parent.mkdir()
    host.write_text("# Our notes\n", encoding="utf-8")
    git(root, "add", "-f", "notes/AGENTS.md")
    _append(root / CONFIG_FILE, '\n[paths]\nagents_md = "notes/AGENTS.md"\n')
    assert (
        run_git(root, "check-ignore", "-q", "--no-index", "--", "notes/AGENTS.md").returncode == 0
    )
    _upgrade(root, tmp_path)
    text = host.read_text(encoding="utf-8")
    assert text.startswith("# Our notes\n") and "keelline:harness:begin" in text


@needs_git
def test_an_artifact_kept_out_of_git_is_written_and_removed_where_git_ignores_it(
    tmp_path: Path,
) -> None:
    # `[artifacts] local` asks for exactly this: the file under `.keelline/local/artifacts/`,
    # which the footprint's ignore block keeps out of git. Mutation (advisory): drop the
    # exemption -> uninstall refuses its removal, and the last assertion reddens.
    root = initialised(
        tmp_path,
        document=f'[keelline]\nversion = "{keelline.__version__}"\n\n[project]\nname = "widget"\n'
        '\n[artifacts]\nlocal = ["roadmap"]\n\n[ci]\nmode = "none"\n',
    )
    local = ".keelline/local/artifacts/docs/roadmap.md"
    assert run_git(root, "check-ignore", "-q", "--", local).returncode == 0
    _uninstall(root, tmp_path)
    assert not (root / local).exists()


def test_outside_a_repository_there_is_no_diff_to_hide_from(tmp_path: Path) -> None:
    # No work tree, so no guard: `check-ignore` cannot answer, and `rev-parse` says why.
    root = tmp_path / "widget"
    root.mkdir()
    (root / ".gitignore").write_text(".env\n", encoding="utf-8")
    (root / ".env").write_text(ENV_TEXT, encoding="utf-8")
    (root / CONFIG_FILE).write_text(
        f'[keelline]\nversion = "{keelline.__version__}"\n\n[project]\nname = "widget"\n\n'
        '[paths]\nagents_md = ".env"\n\n[ci]\nmode = "none"\n',
        encoding="utf-8",
    )
    init(
        root, machine=tmp_path / "absent.toml", runner=LsRemote(), yes=True, dry_run=False, ci=False
    )
    assert "keelline:harness:begin" in (root / ".env").read_text(encoding="utf-8")


@needs_git
def test_a_check_ignore_that_cannot_answer_inside_a_repository_refuses(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A guard that cannot answer must not read as a pass. Mutation (advisory): return instead of
    # refusing after `rev-parse` -> the upgrade runs and this reddens.
    root = initialised(tmp_path)

    def failing(where: Path, *args: str, **kwargs: object) -> tuple[int, str]:
        if args[0] == "check-ignore":
            return 128, ""
        return git_run(where, *args)

    monkeypatch.setattr(module, "git_run", failing)
    # Something to write, so there is something to ask about.
    (root / "docs" / "roadmap.md").unlink()
    before = snapshot(root)
    with pytest.raises(Refusal) as refused:
        _upgrade(root, tmp_path)
    assert str(refused.value) == UNANSWERED
    assert_snapshot_unchanged(root, before)
